---
- name: Setup members array
  set_fact:
    github_members: []

- name: Create the {{ github_keys_install_user }} user
  user:
    name: "{{ github_keys_install_user }}"
    shell: /bin/bash
    password: "*"
  become: true
  when: github_keys_create_install_user

- name: Create ssh folder for {{ github_keys_install_user }}
  file:
    path: /home/{{ github_keys_install_user }}/.ssh
    state: directory
    mode: 0700
    owner: "{{ github_keys_install_user }}"
    group: "{{ github_keys_install_user }}"
  become: true

- name: Clear ssh grouping folder for {{ github_keys_install_user }} if forced
  file:
    path: /home/{{ github_keys_install_user }}/.ssh/source_keys
    state: absent
  become: true
  when: github_keys_force_refresh

- name: Create ssh grouping folder for {{ github_keys_install_user }}
  file:
    path: /home/{{ github_keys_install_user }}/.ssh/source_keys
    state: directory
    mode: 0771
    owner: "{{ github_keys_install_user }}"
    group: "{{ github_keys_install_user }}"
  become: true

- name: Clear old organization folders from previous versions of the role
  file:
    path: /home/{{ github_keys_install_user }}/.ssh/{{ github_keys_github_org }}_keys
    state: absent
  become: true
  with_items: "{{ github_keys_github_orgs }}"
  loop_control:
    loop_var: github_keys_github_org

- include_tasks: org_keys.yml
  with_items: "{{ github_keys_github_orgs }}"
  loop_control:
    loop_var: github_keys_github_org

- name: Add specific github members to the access array
  set_fact:
    github_members: "{{ github_members | union(github_keys_github_users) }}"

- name: Determine the existing keys installed
  find:
    paths: /home/{{ github_keys_install_user }}/.ssh/source_keys
    patterns: "*.keys"
  register: existing_keys_raw

- name: Normalize github usernames
  set_fact:
    github_members: "{{ github_members | map('lower') | list }}"

- name: Expecting to install keys for these github members
  debug:
    var: github_members
    verbosity: 1

- name: Determine Existing github usernames with keys on the server
  set_fact:
    existing_keys: "{{ existing_keys_raw.files | map(attribute='path') | map('regex_replace', '.*/(.*).keys', '\\1') | list }}"

- name: Found these existing keys installed
  debug:
    var: existing_keys
    verbosity: 1

- name: Determine access to removed
  set_fact:
    removing_members: "{{ existing_keys | difference(github_members) }}"

- name: Found these members to remove
  debug:
    var: removing_members
    verbosity: 1

- name: Tell me if the next step won't do anything intentionally
  debug:
    msg: No members to remove from the server
  when: removing_members | length < 1

- name: Clear keys that should no longer have access
  file:
    path: "/home/{{ github_keys_install_user }}/.ssh/source_keys/{{ clear_github_member }}.keys"
    state: absent
  become: true
  with_items: "{{ removing_members }}"
  loop_control:
    loop_var: clear_github_member

- name: Get keys for expected members
  get_url:
    url: "https://github.com/{{ expected_github_member }}.keys"
    dest: "/home/{{ github_keys_install_user }}/.ssh/source_keys/{{ expected_github_member }}.keys"
    owner: "{{ github_keys_install_user }}"
    group: "{{ github_keys_install_user }}"
  with_items: "{{ github_members }}"
  loop_control:
    loop_var: expected_github_member
  become: true

- name: Assemble additional keys into single file for {{ github_keys_install_user }}
  template:
    src: templates/additional_keys.j2
    dest: /home/{{ github_keys_install_user }}/.ssh/source_keys/_additional_keys
    owner: "{{ github_keys_install_user }}"
    group: "{{ github_keys_install_user }}"
  become: true

- name: Assemble all keys into single authorized keys file for {{ github_keys_install_user }}
  assemble:
    backup: yes
    src: /home/{{ github_keys_install_user }}/.ssh/source_keys
    dest: /home/{{ github_keys_install_user }}/.ssh/authorized_keys
    owner: "{{ github_keys_install_user }}"
    group: "{{ github_keys_install_user }}"
  become: true
