---
- name: Get {{ github_keys_github_org }} members
  uri:
    url: https://api.github.com/orgs/{{ github_keys_github_org }}/members
    method: GET
    status_code: 200
    body_format: json
    return_content: yes
  register: org_members_json

- name: Store public organization members for {{ github_keys_github_org }}
  set_fact:
    org_members: "{{ org_members_json.json | json_query('[*].login') }}"

- name: Add public organization members for {{ github_keys_github_org }}
  set_fact:
    github_members: "{{ github_members | union(org_members) }}"

- name: Clear local registers for organization members
  set_fact:
    org_members: ""
    org_members_json: ""
