---
- name: Get {{ github_keys_github_user }} keys
  get_url:
    url: "https://github.com/{{ github_keys_github_user }}.keys"
    dest: "/home/{{ github_keys_install_user }}/.ssh/source_keys/{{ github_keys_github_user }}.keys"
    owner: "{{ github_keys_install_user }}"
    group: "{{ github_keys_install_user }}"
  become: true
  become_user: "{{ github_keys_install_user }}"

